### ISSUE TITLE
プルリクテンプレート設定

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_javascript#2]
プルリクテンプレートを設定します

**Comment by sugasaki-atsushi** [comment]
プルリクのテンプレートちょっとわかりにくくない？
READMEってなんやろ？って思ってしまう
前に送ったこれはどうだろう？


---

## :clap: 解決する issue
- close #0
- close #0
## ⛏ 変更内容


- xxxxxx
- xxx
## 📸  スクリーンショット
