### ISSUE TITLE
ゲーム画面にリセット機能を追加する

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_javascript#36]
### リセットボタン仕様

- リセットボタンは常に表示、通常時は非アクティブ

![js12](https://user-images.githubusercontent.com/70632124/94097420-710a3a80-fe61-11ea-921d-47242f0907ae.PNG)

- Win表示が出たときにアクティブ化

![js12_1](https://user-images.githubusercontent.com/70632124/94097436-75365800-fe61-11ea-8e2b-a5c3124a210c.PNG)

- リセットボタンを押すことで最初の状態に戻る

![js12](https://user-images.githubusercontent.com/70632124/94097480-8717fb00-fe61-11ea-957d-bbb04678541d.PNG)

- 最初の状態に戻るときにボタンも非アクティブに

**Comment by sugasaki-atsushi** [comment]
いいですね。これで進んでみましょう

**Comment by sugasaki-atsushi** [comment]
@Shirahamah 
これ、パネルが１００個あったときに、途中で、やっぱリセットーしたい
となったときはどうしましょう

**Comment by Shirahamah** [comment]
### 仕様案

- 常にアクティブにしておく
- 最初は非アクティブ、Win表示が出たときにアクティブに変更
- 最初は非アクティブ、Win、Lose関係なく1つでもクリックされたらアクティブに変更
- 最初は非アクティブ、規定回数以上クリックされたらアクティブ
- スタートボタン、リセットボタンを配置、スタートボタンが押されたらリセットボタンをアクティブに変更
- 最初はスタートボタンのみ表示、スタートボタンを押したらゲーム画面、リセットボタンを表示
